FROM node:20-alpine

WORKDIR /src/app

COPY package* .
RUN npm install

COPY . .

# DATABASE_URI=
# NEXT_PUBLIC_DOMAIN=http://localhost:3000
# NEXT_PUBLIC_API_DOMAIN=http://localhost:3000/api
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# NEXTAUTH_URL=http://localhost:3000
# NEXTAUTH_URL_INTERNAL=http://localhost:3000
# NEXTAUTH_SECRET=
# CL0UDINARY_CLOUD_NAME=
# CLOUDINARY_API_KEY=
# CLOUDINARY_API_SECRET=

EXPOSE 3000

CMD [ "npm","run","dev" ]